### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by djeraseit** [yriveiro/php-backoff#7]
If the API returns an error such as: Array ( [errors] => Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service. ) 

How would you implement this using your library?

**Comment by yriveiro** [comment]
Hi @djeraseit,

Maybe something like this? 

```php
$attempt = 1;  
$backoff = new Backoff();
try
    do {
        $time = $backoff->fullJitter($attempt);
        $attempt++;
        usleep($time);
        $response = $http->get('http://myservice.com/user/1');
    } while (isset($response['errors']));
} catch (Yriveiro\Backoff\BackoffException $e) {
    // Handle the exception
}
```

First request will be throttled using a minimal time, that will help to do some contention if the call is done in a busy loop.
